<a href="https://colab.research.google.com/github/sanquaorg/Machine-Learning---CSE-305/blob/main/Lab_2_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **19CSE305: MACHINE LEARNING LAB 2**

ROLL NUMBER: 

Q1)

In [ ]:
import math
p = float(input("Enter the principal amount"))
t = float(input("Enter the time in years"))
r = float(input("Enter the rate of interest"))
n = int(input("Enter the number of times interest applied per time period"))
a = math.pow(p*(1+(r/n)),(n*t))
ci = a-p
print(ci)

Enter the principal amount1
Enter the time in years1
Enter the rate of interest1
Enter the number of times interest applied per time period1
1.0


Q2)

In [ ]:
list1 = []
mem = list1.append(input("Enter a string"))
# for i in list1:

  # occurence.append(count)

Enter a stringsanjay


Q3)

In [ ]:
num = (int(input("Enter a number")))

bi = bin(num)[2:]
num_str = str(bi)
b=[]
for i in len(num_str) :
  b.append(num_str[i])
print(b)

Enter a number12


TypeError: ignored

1## Python Basic Exercises

1. Get the values P,t,R from user and calculate compound interest. Formula to calculate compound interest annually is given by: 
        A = P(1+R/100)*t
        CI = A – P
        Input : Principle, Time, Rate
        Output : Compound Interest
2. Given a list of strings (Entered by the user), write program to get a percentage share of each word in the strings list.
        percentage = (Occurrence of a word / Total words) * 100
3. Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’ (entered by the user), write a Python function that returns true if binary representation of 'x' is palindrome and false if not.
4. Write a program to check if all digits of a number divide it. Given a number n (entered by the user), find whether all digits of n divide it or not.
5. Given a list of numbers (entered by the user), write a program to find the second largest number in that list.
        Input: [1, 2, 3, 4 ,5]
        Output: 4

## Numpy Basic Exercises

1. Create a 3D array of shape 4*5*2 that contains random decimal numbers between 1 and 10.
2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3. Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5. Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

Q1)

In [ ]:
import numpy as np
arr = np.random.randint(1,10, size=(4,5,2))
arr

array([[[7, 6],
        [6, 1],
        [1, 2],
        [7, 7],
        [7, 2]],

       [[4, 1],
        [9, 9],
        [1, 1],
        [3, 3],
        [3, 6]],

       [[6, 3],
        [3, 2],
        [3, 4],
        [5, 5],
        [5, 9]],

       [[3, 6],
        [1, 6],
        [9, 6],
        [9, 1],
        [7, 8]]])

Q2)

In [ ]:
arr = np.random.rand(4)
arr1 = arr.reshape(2,2)
print(arr)
arr1

[0.50349829 0.11301578 0.98135582 0.33019247]


array([[0.50349829, 0.11301578],
       [0.98135582, 0.33019247]])

Q3)

In [ ]:
arr = np.array([20,30,15,23,34])
arr1=[]
for i in arr:
  j=(i*1.8)+32
  arr1.append(j)
print(arr1)


[68.0, 86.0, 59.0, 73.4, 93.2]


Q4)

In [ ]:
arr = np.arange(5)
arr
print(arr.ndim)
print(len(arr))
print(arr.nbytes/len(arr))


1
5
8.0


Q5)

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(arr[0][1])
print(arr[0][2])
print(arr[1][1])
print(arr[1][2])

2
3
6
7
